### ISSUE TITLE
How use electron in vuex actions?

### ISSUE THREAD

**Issue by cawa-93** [SimulatedGREG/vue-electron#1]
I need use electron.dialog in vuex action

**Comment by SimulatedGREG** [comment]
@cawa-93 

You can either import electron itself or import Vue, as `$electron` should still be attached.

```js
import { dialog } from 'electron'

/* or */

import Vue from 'vue'
Vue.$electron.dialog({ ... })
```

**Comment by JohnRSim** [comment]
This returns as undefined for me - within Vuex store
```
import Vue from 'vue';
console.log(Vue.$electron);
```

This works though
```
import { dialog } from 'electron';
```

Did something change?
