### ISSUE TITLE
Cannot find module "fs"

### ISSUE THREAD

**Issue by joedawson** [SimulatedGREG/vue-electron#2]
Hey,

When I try and use, I seem to get the following error:

> Cannot find module "fs"

Here's my code:

```js
import Vue         from 'vue';
import VeeValidate from 'vee-validate';
import VueElectron from 'vue-electron';
import { sync }    from 'vuex-router-sync';

import App         from './components/App.vue';
import store       from './store';
import router      from './router';

Vue.use(VeeValidate);
Vue.use(VueElectron);

sync(store, router);

const app = new Vue({
	el: '#app',
	router,
	store,
	template: '<App/>',
	components: { App }
});
```

In my root component (`App.vue`), I'm just trying to log the current version of my app.

```js
mounted: function() {
    console.log(this.$electron.remote.app.getVersion());
},
```

I'm using webpack to compile my app.

Any ideas? Thanks in advance.

**Comment by SimulatedGREG** [comment]
@JoeDawson 

Make sure to have your webpack's `target` set to `electron-renderer` so the node specific modules are exposed properly.

**Comment by joedawson** [comment]
Hey @SimulatedGREG,

Thanks for your reply. I've added this to my config, but I appear to be seeing this error now:

> This relative module was not found:
>
> * ./package in ./~/got/index.js

I'm using https://github.com/JeffreyWay/laravel-mix as wrapper for Webpack, it just made it easier to get going with Webpack.

So my `webpack.mix.js` looks like this:

```js
const { mix } = require('laravel-mix');

mix.js('src/js/app.js', 'app/assets/js')
   .sass('src/sass/app.scss', 'app/assets/css').options({
      processCssUrls: false
   });

mix.webpackConfig({
    target: "electron-renderer"
});
```

Do you have any idea why I might be getting this? If not, do you have an easy way to for me to simple compile my Vue and SaSS?

Thanks!

**Comment by SimulatedGREG** [comment]
@JoeDawson Sorry for late reply.

I'm assuming this setup is using `vue-loader` so you should be able to just install `node-sass` and `sass-loader` in your project and use the `lang="scss"` on your `<style>` tags. From there you can `@import` your Sass files. https://vue-loader.vuejs.org/en/configurations/pre-processors.html for more info.

**Comment by SimulatedGREG** [comment]
Going to close this since it isn't directly related to `vue-electron`. Feel free to comment back if needed.

**Comment by boxsnake** [comment]
I think it's better to add note on `vue-electron`'s readme, with someting like:
**Note:** Webpack config field `target` should be set to `electron-renderer` if you create the vue project yourself.
