### ISSUE TITLE
How do you make a new browser window?

### ISSUE THREAD

**Issue by david-saint** [SimulatedGREG/vue-electron#4]
Hi,
Thanks for this project, it's a life saver 

I am working with electron-vue and I want to open a new browser window on click of a button but I'm not sure how to go about it.

**Comment by Splode** [comment]
The better place to have this question answered is by the [official Electron API documentation](https://electronjs.org/docs). Specifically, you'll want to look at the `BrowserWindow`, `ipcMain` and `ipcRenderer` modules.

**Comment by Piterden** [comment]
```js
new BrowserWindow(options)
```
Isn't it?

**Comment by SimulatedGREG** [comment]
This is not a direct issue, and I will be closing. Please know that the presence of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

**`electron`**
* https://electron.atom.io/docs/

**`vue`**
* https://vuejs.org/v2/guide/
* https://forum.vuejs.org/
* https://chat.vuejs.org/
